/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    Categories: typeof import('./components/Categories.vue')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    DocumentRenderer: typeof import('./components/DocumentRenderer.vue')['default']
    FeaturedArticles: typeof import('./components/FeaturedArticles.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Mission: typeof import('./components/Mission.vue')['default']
    Post: typeof import('./components/Post.vue')['default']
    Quote: typeof import('./components/common/Quote.vue')['default']
    RecentPosts: typeof import('./components/RecentPosts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VoiceOfKhalifa: typeof import('./components/VoiceOfKhalifa.vue')['default']
  }
}
